### ISSUE TITLE
Implement accelerated functions

### ISSUE THREAD

**Issue by thiloplanz** [thiloplanz/glulx-typescript#1]
http://eblong.com/zarf/glulx/glulx-spec_2.html#s.17

To improve performance, Glulx incorporates some complex functions which replicate code in the Inform library. 

FyreVM additionally offers a "setVeneer" call (not sure what the difference is), and notes that 

> Inform games rely heavily on these routines, and substituting our C# versions for the Glulx versions in the story file can increase performance significantly

**Comment by curiousdannii** [comment]
Will this project be using a JIT at all?

**Comment by thiloplanz** [comment]
A JIT (presumably compiling Glulx code down to asm.js-compatible Javascript functions) would indeed be great, ideally completely obviating the need to have these custom-built acceleration function by improving performance across the board for any function.

**Comment by thiloplanz** [comment]
I opened ticket #8 for implementing JIT compilation to JS (without mentioning asm.js compatibility, it seems that one needs to develop in C to get proper tools for that, at least Typescript is not a good choice).
