### ISSUE TITLE
Error in Angular2 App

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#10]
I get the following when running TSC...

D:\Dropbox\projects\glulx-typescript\example\web\angular2>tsc -d --out ../webworket.js ../../../web/webworker.ts
../../../core/Veneer.ts(117,36): error TS4078: Parameter 'slot' of exported function has or is using private name 'VeneerSlot'.

**Comment by thiloplanz** [comment]
... and after fixing this, building the demo app fails on a fresh checkout of the Angular2 typings, because some things have changed between Angular v2.0.0-alpha.28 and v2.0.0-alpha.37.

> app.ts(15,37): error TS2305: Module '"angular2/angular2"' has no exported member 'coreDirectives'.

**Comment by thiloplanz** [comment]
This should compile (and work...) now.  You will have to run the `tsd` command again (see updated README).

**Comment by ChicagoDave** [comment]
http://127.0.0.1:8080/angular2/ should be http://127.0.0.1:8080

**Comment by ChicagoDave** [comment]
Oh the directions are unclear how to run the angular project. You have to set your directory to /web and then run http://127.0.0.1:8080/angular2/.

**Comment by thiloplanz** [comment]
Re-opening as the build steps are failing again, because Angular2 is no longer using `tsd`. Need to update to the latest Angular2 (on the plus side, they are no longer in "alpha").

**Comment by thiloplanz** [comment]
I've updated `example/web/angular2` for the current Angular2 beta release.
The build steps are now somewhat simpler, all can be done with `npm`.
 
     cd example/web/angular2
     npm install
     npm start

I've also replaced the WebWorker with EngineWrapper.
