### ISSUE TITLE
EngineWrapper in Browser

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#15]
The node CLI version is great. I plan to use that for testing tools. This next bit is for the browser...

```
import {fyrevm} ...

EngineWrapper wrapper = new fyrevm.engineWrapper();
wrapper.SendCommand(mystory.ulx, mystory.sav, command)
var results = wrapper.Channels;
wrapper.SendCommand(command);
results = wrapper.Channels;
```
I'd add that I would like to glue the EngineWrapper to the DOM so later I
can do...

```
document.FyreVM.SendCommand(...)
results = document.FyreVM.ChannelData;
```

**Comment by thiloplanz** [comment]
Hmm. This seems to be quite similar to how the "WebWorker" already works. In fact, it uses the same EngineWrapper code that the node CLI version does. 

Probably the only difference is that "WebWorker" runs asynchronously.

I'll take this task to mean "change the EngineWrapper API from being call-back based to synchronous". It could then be used directly on the main browser thread (similar to how you describe it above) or via API calls to Web Worker or server-side (where the call would in turn be forwarded to an EngineWrapper running there).

**Comment by ChicagoDave** [comment]
My jnderstanding is that you implemented the web-worker to improve performance on the UI thread. I get it, but that also complicates my future usage patterns and it complicates testing.

I'm willing to pay for the JIT effort if that's beyond casual work. I think it needs to be done before this is truly viable.

**Comment by thiloplanz** [comment]
I have added an example of embedding EngineWrapper directly in a browser page (not using a web worker): example/web/engineWrapper

**Comment by ChicagoDave** [comment]
Try the attached ulx file. It bombs immediately.

[shadow-2.1.ulx.zip](https://github.com/thiloplanz/glulx-typescript/files/229212/shadow-2.1.ulx.zip)

**Comment by ChicagoDave** [comment]
I tried running this with the game.ulx file and I get:

D:\Dropbox\GitHub\glulx-typescript-thilo\glulx-typescript\example\node\engineWrapper>node engineWrapper.js game.ulx test "look"
Unexpected engine state: 2
D:\Dropbox\GitHub\glulx-typescript-thilo\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3285
                throw new Error("Illegal state, engine is not waiting for line input");
                ^

Error: Illegal state, engine is not waiting for line input
    at EngineWrapper.receiveLine (D:\Dropbox\GitHub\glulx-typescript-thilo\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3285:23)
    at Object.<anonymous> (D:\Dropbox\GitHub\glulx-typescript-thilo\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3400:25)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by thiloplanz** [comment]
The "game.ulx" included in the repo (`example/web/game.ulx`) is just a placeholder that prints out a message and exists the engine. It does not accept an input command and has no capability to handle save games.  I'll update engine wrapper to handle that scenario (but it won't be able to do much more than just output the message and exit).

**Comment by ChicagoDave** [comment]
Oops. I guess I need to make a test game.

**Comment by ChicagoDave** [comment]
Looks like we need an option to run without a command to start and report the initial load channel data. As it is, the first execution skips turn 1 and jumps to turn 2.

    node engineWrapper.js ifpress.ulx mySession --start

then

    node engineWrapper.js ifpress.ulx mySession "north"
    node engineWrapper.js ifpress.ulx mySession "south"
    node engineWrapper.js ifpress.ulx mySession "south"

[ifpress.zip](https://github.com/thiloplanz/glulx-typescript/files/230753/ifpress.zip)

I would also consider emitting sessionName.session.{turn}, but that's probably a separate discussion. I'd want to store the session data for each turn along with all emitted JSON somehow. Like a database of some sorts. I could look up turn x, get the session data and the emitted JSON and "reset" the UI. Whether this goes to a file or into local storage should be adaptable.

**Comment by thiloplanz** [comment]
> Looks like we need an option to run without a command to start and report the initially emitted channel data. 

This was supposed to happen when you run the tool without a command (`node engineWrapper.js ifpress.ulx mySession`). The output not being printed is a bug, hopefully fixed now.

> I would also consider emitting sessionName.session.{turn}

It should be pretty easy to do that. Take a look at how the session file is generated. 

Such a mechanism would also compensate for the loss of "undo" functionality (you could intercept an "undo" command entered by the user and just inject the session at a previous turn).

If you end up collecting a lot of session files, implementing Quetzal compression (#6) may be of interest to reduce their size.

> Whether this goes to a file or into local storage should be adaptable.

The EngineWrapper module itself is not concerned with that. It only creates "Quetzal" objects that the calling application can then store as appropriate. The node example saves to a file, the web examples save to localStorage.

**Comment by ChicagoDave** [comment]
I forked and added turn-based sessions and branching for the node engineWrapper and created a pull request.

**Comment by ChicagoDave** [comment]
On to the web version. I think we don't need the FileReader bit as it is. I think expecting the author to translate a ulx file into a js import is fine, the same as Quixe.

So then on page load, we grab an expected variable storyFileData, and load that.

Also, instead of SetText, I just want to add all of the channel data to either the DOM or to the FyreVM object. So then I can use them as I see fit.

**Comment by ChicagoDave** [comment]
Probably need to think this through for the web EngineWrapper...

(pseudo code)
onPageLoad (event):
    create EngineWrapper object

    if storyFileImageData === undefined then
        display missing game file page
        end process
    end-if

    retrireve sessionData from LocalStorage
    if sessionData === undefined then
         load storyFileImageData
         write channel data to DOM or FyreVM object
         write sessionData to LocalStorage
    else
         load storyFileImageData with sessionData
         write channel data to DOM or FyreVM object
         write sessionData to LocalStorage
    end-if

    // this is separate from the engine processing and optional
    {app framework starts/executes}

There are varied ways to handle session data. Do we allow different sessions? Do we allow branching? I can work through these separately though.

**Comment by thiloplanz** [comment]
> On to the web version. I think we don't need the FileReader bit as it is. I think expecting the author to translate a ulx file into a js import is fine, the same as Quixe.

I have updated the `web/engineWrapper` example to load `ifpress.ulx` directly without having the user select a file. The URL can easily be changed in the game.html file (script tag at the end).

I don't think it's necessary to transcode the game image into a JS file just to be able to load it, but that can be done, too. I have added a EngineWrapper.loadFromBase64 helper method to facilitate that.

If people are fine with running a pre-processing step on the ULX to convert it to Javascript, though, that opens up the possibility to do some ahead-of-time compilation and other optimizations as well. Will think about it in my (very slowly) ongoing JIT efforts.

> There are varied ways to handle session data. Do we allow different sessions? Do we allow branching?

I think we can start by building on the normal "save" command. It allows for having a UI where the user can select between multiple savegames when saving or restoring, thereby "branching" as much as she wants.

This means explicit session management by the player, though: When the page opens, it starts the game at the beginning, one has to type "restore" to go back to yesterday's session (and one had to have typed "save" before closing the window yesterday). Maybe a bit old-school (but, hey, so are text adventures...)

**Comment by ChicagoDave** [comment]
I'd rather not have the browser do anything where UI is concerned. All UI should be done by the underlying HTML designed by my templates or author-additions. So for save sessions, we just need a mechanism to do it and store the files in Local Storage.

If the author wants to add the ability to save sessions to disk, we should allow that, but not turn it on by default.

I'm not concerned with "standard" UI behavior. Anyone that wants standard IF can use out of the box Glulx/Quixe.

So the in-game save and restore commands, along with an FileReader code is deprecated.

We just need EngineWrapper.Save and .Load. Save would return a byte array and Load would accept a byte array.

Then we can have add-ons for file save/load or to use Local Storage.

**Comment by ChicagoDave** [comment]
Regarding transcoding ulx file to JS. I think (correct me if I'm wrong) that you're saying we can just locate the ulx file relative to the html page. The problem with some scenarios is that an author may run into mime type issues (since ulx is not a common app type). For instance, if the author hosts their story on IIS, they'd have to add ulx=application/glulx to the mime type definitions.

It's better to be safe and turn the ulx into a local variable in a JS/TS script and loaded by the VM.

When I get ifpress going, there will be a gulp process to do this for the author automatically. Every time they compile in Inform 7, I'll take the resulting ulx, transcode it, and update the html package their creating.

**Comment by ChicagoDave** [comment]
So I know we already have an EngineWrapper, but I consider this a low-level interface I'd never want an "author" to see or mess with. It's too close to bare metal. My idea has been to add another layer of abstraction on top of the EngineWrapper to more innocently meld with HTML without having any opinion on I/O. I don't want this "manager" to care about inputs, know nothing of HTML, and only sit waiting for commands. When a turn is completed, it will call an author-defined call back with the channel data. The Save/Load stuff I'm still waffling on, but I think that needs to be some sort of extension class. So maybe we have a FileSystemSessionData and a LocalStorageSessionData. Even so, the last turn's session data (Quetzal) should be in a property of the manager class to be read if needed by the author. I have the basic idea coded in:

https://github.com/ChicagoDave/fyrevm-web/blob/master/projects/Stop%20the%20IFPress!.fyrevm/FyreVMWeb.ts

Look at that tell me what you think.

**Comment by thiloplanz** [comment]
By "author" you mean someone who also creates (or at least customizes) the HTML/Javascript player environment for the game (as opposed to "just" writing the game image using Inform)?

It absolutely makes sense to offer a higher-level framework to these authors, one that takes care of integrating with the various browser technologies and maybe also makes some opinionated choices about UI frameworks and other Javascript libraries, so that the author can focus on the content part (defining what channels there are, how they are to be displayed, etc). 

I suppose that is what fyrevm-web is for, right? 
Please let me know if you find anything that fyrevm-web requires from EngineWrapper that the latter fails to provide. I'll also try to port the examples over to use fyrevm-web instead of EngineWrapper to see how that goes.

I'm closing this issue now, let's open new issues for those specific requirements.

As for the session data, the EngineWrapper class does provide a "getUndoState" method, but it seems that Inform code generates the Quetzal for the previous step only as part of executing the next one (so that "getUndoState" returns something that is two turns behind). That is why the command-line tool sends a dummy "look" command after the real command immediately before grabbing the session state Quetzal.
