### ISSUE TITLE
IO Separation

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#25]
So when I say FyreVMWeb shouldn't be opinionated, this will likely extend to EngineWrapper.

EngineWrapper should never have any concept of HTML or how input is implemented. It should simply accept input as a string (whether it's key or line doesn't matter to it), execute the command, place the channel data in a public property, place the session data in a public property, place the last command in a public property, set a property stating whether a key or line is expected and execute a callback to tell the hosting class that it's done its work and the hosting class can do whatever it wants.

A save command should simply expose the quetzal data as a public property. It should never expect a pointer or anything else from its hosting class.

A load command would receive the session data and proceed normally.

FyreVMWeb.Manager will also not presume anything about HTML or inputs, but it will add channel data to the DOM and execute a callback to tell the "app" that it can "redraw" the screen and set the input type (key or line). The app itself would handle the input and call FyreVM.Manager.sendCommand(text) and the process repeats itself.

I wouldn't mind help with FyreVMWeb.Manager since the dance between Engine <-> EngineWrapper <-> FyreVMWeb.Manager is a delicate one. I'm trying to create a sequence diagram, but it's not trivial.

**Comment by thiloplanz** [comment]
I am not sure what this means. Nothing in EngineWrapper depends on HTML (or even a browser). The code is used by the nodeJS commandline examples. All EngineWrapper does is communicate with the game engine, passing along the input (in the form of line or key input) and the output (in the form of channels, a dictionary of strings). Anything to do with presentation, interacting with the user, managing save games etc is done by the application that embeds EngineWrapper.

**Comment by ChicagoDave** [comment]
Okay I see what you mean. But it's a communication/naming issue. The name of the ts file you use for managing an example is engineWrapper.ts. But the name of the _actual_ core\EngineWrapper.ts is in core.

The code in the example should be called EngineManager.ts or something other than engineWrapper.ts.

But that also is what I'm talking about. Your "Example" class has globals, it's Module-based, and well it's too opinionated (I know it's just a sample, but I'm trying to make it better). This is what I want to replace with FyreVM.Manager, which will wrap core\EngineWrapper.ts and simplify what the user does in their html page.

**Comment by thiloplanz** [comment]
I have ported the "stop-the-press" example (`example/web/engineWrapper`) to use FyreVMManager instead of EngineWrapper and pushed that to fork of fyrevm-web.

https://github.com/thiloplanz/fyrevm-web/tree/master/projects/Stop%20the%20IFPress!.fyrevm/example

It consists of 

* the game image (pre-compiled ULX)
* an HTML page to load the game. It has no external dependencies, just FyreVMManager.
* a tsconfig.json to build the code. This just builds the core and FyreVMManager classes, no custom "game author" code.
* The "game author" code is contained in the HTML page directly. This is mostly for demonstration purpose and to clearly show where FyreVMManager ends and "example"/"game author code" begins (as that distinction has apparently been a bit muddled so far). In a real game, the author would probably want to use Typescript, and compile it by adding it to "tsconfig.json".

**Comment by ChicagoDave** [comment]
Awesome. This is phase 1 for the general use of glulx-typescript. The ifpress version is my next layer, which will take all the channel data and turn it into dom-level properties (document.ifpress.mainChannel, document.ifpress.locationName, etc). It will also fire document.ifpress.outputReady and allow document.ifpress.sendCommand. On top of this I plan to build a CMS for IF. Thank you very much!

**Comment by ChicagoDave** [comment]
For some crazy reason, I can't run your version of stop-the-press.html. I had to put it in IIS to even get to an error (gave me a 404 in WebStorm). It's telling me the .ulx file has wrong magic number...and I recompiled the story and tried again. Same response.

**Comment by ChicagoDave** [comment]
Never mind. I pushed it through debug mode and now it seems to be working properly. I have no clue why it was doing weird things last night.
