### ISSUE TITLE
Compile errors with ES6 target

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#28]
Hey Thilo - I added a react project to fyrevm-web. There seems to be a problem compiling fyrevm. It emits the following and I have no clue what I did to cause the problem. If you have an answer, please let me know. Thanks.

D:\Dropbox\GitHub\fyrevm-web\glulx-typescript\Engine.ts
Error:(951, 31) TS2345: Argument of type 'Uint8Array' is not assignable to parameter of type 'ArrayBuffer'.
D:\Dropbox\GitHub\fyrevm-web\glulx-typescript\MemoryAccess.ts
Error:(59, 12) TS2322: Type 'Uint8Array' is not assignable to type 'ArrayBuffer'.
 Types of property '[Symbol.toStringTag]' are incompatible.
 Type '"UInt8Array"' is not assignable to type '"ArrayBuffer"'.
D:\Dropbox\GitHub\fyrevm-web\glulx-typescript\Quetzal.ts
Error:(91, 22) TS2345: Argument of type 'Uint8Array' is not assignable to parameter of type 'ArrayBuffer'.
D:\Dropbox\GitHub\fyrevm-web\glulx-typescript\UlxImage.ts
Error:(121, 29) TS2345: Argument of type 'Uint8Array' is not assignable to parameter of type 'ArrayBuffer'.
Error:(128, 29) TS2345: Argument of type 'Uint8Array' is not assignable to parameter of type 'ArrayBuffer'.

**Comment by thiloplanz** [comment]
That is interesting. The error message does seem correct. I wonder why I am not getting this. Which version of the Typescript compiler are you using? I was on 1.8.9 (which did not complain) and updated to 1.8.10 now (which also accepts the code).

I will change the code to be more strict about ArrayBuffer and Uint8Array (a first stab broke the unit tests, so this needs some more testing and I would feel better if my compiler also issued this error). 
Do you have your React codebase (the one that raises this error) on Github, too?

**Comment by ChicagoDave** [comment]
It's in FyreVM-web/projects/cloak of darkness/react

The JavaScript folder has a full implementation of a plain version.

**Comment by thiloplanz** [comment]
>  The error message does seem correct. I wonder why I am not getting this.

I was able to reproduce the problem. It happens when you compile with `-target es6`.

**Comment by ChicagoDave** [comment]
Awesome. Do we close this?

**Comment by thiloplanz** [comment]
I've updated the code, it just now work with all compile targets, please try again with ES6.
If you find any more bugs with your React version, please see if changing the target to ES3 or ES5 makes a difference (and if it does, reopen this issue).

**Comment by ChicagoDave** [comment]
ES5 works. Thanks again!
