### ISSUE TITLE
Lists cause problems

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#33]
Running the following code through glulx-typescript...
[TestListFyreVM.zip](https://github.com/thiloplanz/glulx-typescript/files/9940874/TestListFyreVM.zip)

```
"Test List FyreVM" by DC

Include FyreVM Support by David Cornelson.

The kitchen is a room.

The player is in the kitchen.

The papa is a list of text that varies.

When play begins:
	let papa be {"jiji"};
	
The Backyard is south of the kitchen.

After going south:
	add "hjhj" to papa;
	say "papa has [the number of entries in papa] entries."

```

...responds with...

```
{"MAIN":"\n\n\nTest List FyreVM\nAn Interactive Fiction by DC\nRelease 1 / Serial number 221104 / Inform 7 build 6M62 (I6/v6.33 lib 6/12N) SD\n\n>kitchen05401"}
C:\Users\david\Downloads\TestGlulx\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3506
    fs.writeFileSync(saveFile, new Buffer(new Uint8Array(engine.getUndoState().serialize())));

TypeError: Cannot read properties of null (reading 'serialize')
    at Object.<anonymous> (C:\Users\david\Downloads\TestGlulx\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3506:79)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.0
```

**Comment by thiloplanz** [comment]
How these session files work is that we save the "undo state" of the game.

At the moment, that undo state is generated by the engine wrapper issuing a "look" command to the game. It seems like that test image does not respond to "look"?

When I run it through "runGameImage.js" I get this output:
```
% node runGameImage.js ~/Downloads/TestListFyreVM.ulx



Test List FyreVM
An Interactive Fiction by DC
Release 1 / Serial number 221104 / Inform 7 build 6M62 (I6/v6.33 lib 6/12N) 

You can see a knife and an ethereal cabin here.

>kitchen05401[cycles: 25317  millis: 53]
 look
[cycles: 88  millis: 0]
```

No output text to the look command.

Does this make sense to you? Do you know how we could fix this (in the engine wrapper or the game image)?

**Comment by ChicagoDave** [comment]
Yeah something is fishy with the compile with Inform 6M62. The FyreVM library hasn't changed, so not sure why anything else has. I'm looking too.

**Comment by ChicagoDave** [comment]
Oh duh. It's the wrong FyreVM extension. The latest is FyreVM Core. This came from a different person, so I will notify him. Try the attached file.

**Comment by thiloplanz** [comment]
I tried the file attached to this ticket ([TestListFyreVM.zip](https://github.com/thiloplanz/glulx-typescript/files/9940874/TestListFyreVM.zip)), and got the output I mentioned. Is that the file you meant? 

It seems that that file does not respond to "look".

**Comment by ChicagoDave** [comment]
Let's try that again.
[TestListFyreVM-withCore.zip](https://github.com/thiloplanz/glulx-typescript/files/9954724/TestListFyreVM-withCore.zip)

**Comment by thiloplanz** [comment]
Yeah, that new file seems to work for me. What errors are you seeing?

```
 % node --trace-deprecation engineWrapper.js ~/Downloads/TestListFyreVM-withCore.ulx testSession-withCore
{"MAIN":"\n\nTest List FyreVM\nAn Interactive Fiction by DC\nRelease 1 / Serial number 221105 / Inform 7 build 6M62 (I6/v6.41 lib 6/12N) \n\n","CMGT":"1129138004,text,contentTypes;","INFO":"{ \"storyTitle\": \"Test List FyreVM\", \"storyHeadline\": \"An Interactive Fiction\", \"storyAuthor\": \"DC\", \"storyCreationYear\": \"0\", \"releaseNumber\": \"1\", \"serialNumber\": \"221105\", \"inform7Build\": \"6M62\", \"inform6Library\": \"6.41\", \"inform7Library\": \"6/12N\", \"strictMode\": \"\", \"debugMode\": \"\" }","PRPT":">","LOCN":"kitchen","SCOR":"0","TIME":"540","TURN":"1"}
```

**Comment by ChicagoDave** [comment]
I think that took care of it. The guy that reported the list problem was using the wrong extension for fyrevm.
